import path from 'node:path'
import benchmarkTemplates from '../../../assets/benchmark-templates.json'
import { getDiskSpace } from './disk'
import { fetchJSON } from './fetch'
import {
  getModelsBaseDir,
  resolveDownloadContextById,
  resolveModelsPresence
} from './modelDownloadPaths'
import {
  isPersistableTemplateId,
  RAW_TEMPLATES_BASE,
  TEMPLATE_MODALITY_ORDER,
  type TemplateModality,
  type TemplateSnapshot
} from '../sources/standalone/curatedTemplates'
import {
  hydrateTemplates,
  toTemplateFieldOption,
  type HydratedTemplate
} from '../sources/standalone/templateCatalog'
import {
  formatTemplateSubStatus,
  type TemplateDownloadSummary
} from '../sources/standalone/templateDownloadCore'
import {
  forgetTemplateDownload,
  startTemplateDownloadTask,
  subscribeTemplateDownload
} from '../sources/standalone/templateDownloadTask'
import { resolveTemplateModelsFromJson } from '../sources/standalone/templateModels'
import type { InstallationRecord } from '../installations'
import type { FieldOption } from '../types/sources'
import type { DiskSpaceInfo, ExampleWorkflowDownload } from '../../types/ipc'

/**
 * API-format prompts for performance tests, published beside `templates/` in
 * the workflow_templates repo. Each shares its id with a parent template whose
 * editor workflow supplies the cover image and the model download URLs.
 */
const BENCHMARKS_BASE = RAW_TEMPLATES_BASE.replace(/\/templates$/, '/benchmarks')
/** Same budget as the install picker's "Downloaded" badges. */
const MODELS_PRESENT_BUDGET_MS = 2500

interface BenchmarkTemplate {
  id: string
  modality: TemplateModality
  recommended?: boolean
  snapshot: TemplateSnapshot
}

function isBenchmarkTemplate(value: unknown): value is BenchmarkTemplate {
  const entry = value as Partial<BenchmarkTemplate> | null
  const snapshot = entry?.snapshot
  return (
    isPersistableTemplateId(entry?.id) &&
    TEMPLATE_MODALITY_ORDER.includes(entry!.modality as TemplateModality) &&
    (entry!.recommended === undefined || typeof entry!.recommended === 'boolean') &&
    typeof snapshot?.title === 'string' &&
    typeof snapshot.description === 'string' &&
    typeof snapshot.sizeBytes === 'number' &&
    typeof snapshot.mediaSubtype === 'string'
  )
}

/**
 * Bundled list of the workflows in `benchmarks/`, with offline display metadata.
 * Generated by `scripts/benchmark-templates.mjs`; a malformed entry is dropped
 * rather than reaching a URL or file path.
 */
const BENCHMARK_TEMPLATES: BenchmarkTemplate[] =
  benchmarkTemplates.templates.filter(isBenchmarkTemplate)

function loadExampleCatalog(): Promise<HydratedTemplate[]> {
  return hydrateTemplates(BENCHMARK_TEMPLATES)
}

function editorWorkflowUrl(templateId: string): string {
  return `${RAW_TEMPLATES_BASE}/${encodeURIComponent(templateId)}.json`
}

/** Free space where this installation's models are downloaded, or null when unknown. */
async function modelsDiskSpace(installationId: string): Promise<DiskSpaceInfo | null> {
  try {
    const context = await resolveDownloadContextById(installationId)
    return await getDiskSpace(context ? context.downloadBaseDir : getModelsBaseDir())
  } catch {
    return null
  }
}

/** Picker cards with "Downloaded" badges, plus the disk space their models would use. */
export async function getPerformanceTestExampleCatalog(
  installationId: string
): Promise<{ options: FieldOption[]; diskSpace: DiskSpaceInfo | null }> {
  const catalog = await loadExampleCatalog()
  const [{ presence }, diskSpace] = await Promise.all([
    resolveModelsPresence(
      catalog.map(({ id }) => id),
      installationId,
      async (id) => resolveTemplateModelsFromJson(await fetchJSON(editorWorkflowUrl(id))),
      MODELS_PRESENT_BUDGET_MS
    ),
    modelsDiskSpace(installationId)
  ])
  return {
    options: catalog.map((template) =>
      toTemplateFieldOption(template, presence.get(template.id) ?? false)
    ),
    diskSpace
  }
}

/**
 * Why an example's files could not be fetched: `offline` when the
 * workflow_templates repo is unreachable, `unavailable` when it has no such file
 * (e.g. a benchmark bundled before it was published upstream).
 */
export type ExampleWorkflowFetchFailure = 'offline' | 'unavailable'

export class ExampleWorkflowFetchError extends Error {
  constructor(readonly reason: ExampleWorkflowFetchFailure) {
    super(
      reason === 'offline'
        ? 'Connect to the internet to download example workflows.'
        : 'This example workflow is not available yet.'
    )
    this.name = 'ExampleWorkflowFetchError'
  }
}

export interface PerformanceTestExampleArtifacts {
  template: HydratedTemplate
  editorWorkflow: unknown
  apiWorkflow: unknown
}

export async function loadPerformanceTestExampleArtifacts(
  templateId: string
): Promise<PerformanceTestExampleArtifacts> {
  const template = (await loadExampleCatalog()).find(({ id }) => id === templateId)
  if (!template) {
    throw new Error('This example workflow is unavailable for performance testing.')
  }

  let editorWorkflow: unknown
  let apiWorkflow: unknown
  try {
    ;[editorWorkflow, apiWorkflow] = await Promise.all([
      fetchJSON(editorWorkflowUrl(templateId), { refresh: true }),
      fetchJSON(`${BENCHMARKS_BASE}/${encodeURIComponent(templateId)}.json`, { refresh: true })
    ])
  } catch (error) {
    // Chromium reports a failed connection as `net::ERR_*` (e.g. ERR_NAME_NOT_RESOLVED
    // when offline); a reachable server answering with an error is `HTTP <status>`.
    const message = (error as Error)?.message ?? ''
    if (/\bnet::ERR_/.test(message)) throw new ExampleWorkflowFetchError('offline')
    if (/^HTTP 404\b/.test(message)) throw new ExampleWorkflowFetchError('unavailable')
    throw error
  }
  if (!Array.isArray((editorWorkflow as { nodes?: unknown } | null)?.nodes)) {
    throw new Error('The example workflow template is invalid.')
  }
  return { template, editorWorkflow, apiWorkflow }
}

/** One model download per prepared session, keyed off its stored workflow. */
function exampleDownloadTaskId(workflowFilePath: string): string {
  return `performance-test-download:${path.basename(path.dirname(workflowFilePath))}`
}

function toExampleDownload(summary: TemplateDownloadSummary): ExampleWorkflowDownload {
  return {
    status: summary.status,
    percent: summary.percent,
    message: formatTemplateSubStatus(summary),
    error: summary.error
  }
}

/**
 * Start downloading the models an example workflow needs, in the background.
 * Returns the progress at start; `onProgress` then gets the task's paced
 * progress until it settles.
 */
export function startExampleModelDownload(
  installation: InstallationRecord,
  workflowFilePath: string,
  { template, editorWorkflow }: PerformanceTestExampleArtifacts,
  onProgress: (download: ExampleWorkflowDownload) => void
): ExampleWorkflowDownload {
  const taskId = exampleDownloadTaskId(workflowFilePath)
  startTemplateDownloadTask(
    taskId,
    installation,
    template.id,
    template.sizeBytes,
    { sendOutput: () => {} },
    editorWorkflow
  )
  // The subscription ends when the download settles, or when the workflow is deleted.
  let initial: ExampleWorkflowDownload | undefined
  subscribeTemplateDownload(taskId, (summary) => {
    const download = toExampleDownload(summary)
    if (initial) onProgress(download)
    else initial = download
  })
  // The task was just started under this id, so the subscription reported it at once.
  return initial!
}

/** Stop a prepared example's model download (if any) and drop its state. */
export function cancelExampleModelDownload(workflowFilePath: string): void {
  forgetTemplateDownload(exampleDownloadTaskId(workflowFilePath))
}
